name: design_system
description: my design system package.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: app_icons
      fonts:
        - asset: packages/design_system/assets/fonts/AppIcons.ttf
    - family: Euclid_Circular_A
      fonts:
        - asset: packages/design_system/assets/fonts/Euclid_Circular_A/Euclid_Circular_A_Light.ttf
          weight: 100
        - asset: packages/design_system/assets/fonts/Euclid_Circular_A/Euclid_Circular_A_Medium.ttf
          weight: 300
        - asset: packages/design_system/assets/fonts/Euclid_Circular_A/Euclid_Circular_A_Regular.ttf
          weight: 400
        - asset: packages/design_system/assets/fonts/Euclid_Circular_A/Euclid_Circular_A_SemiBold.ttf
          weight: 500
        - asset: packages/design_system/assets/fonts/Euclid_Circular_A/Euclid_Circular_A_Bold.ttf
          weight: 600
    - family: lato
      fonts:
        - asset: packages/design_system/assets/fonts/lato/Lato-Light.ttf
          weight: 100
        - asset: packages/design_system/assets/fonts/lato/Lato-Medium.ttf
          weight: 300
        - asset: packages/design_system/assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: packages/design_system/assets/fonts/lato/Lato-Semibold.ttf
          weight: 500
        - asset: packages/design_system/assets/fonts/lato/Lato-Bold.ttf
          weight: 600
        - asset: packages/design_system/assets/fonts/lato/Lato-Heavy.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
